---
id: tokyowomenrb1
base_name: scenario
tags:
  - ruby
presentation_date: "2025-03-01"
tags: []
version: 1.0.0
licenses: []
author:
  markup_language:
  name: makicamel
  email: unright@gmail.com
  rubygems_user: makicamel
  slideshare_user:
  speaker_deck_user:
  source_code_uri: "https://github.com/makicamel/tokyowomenrb1"
